=== nitinsingh008/XML-Analytics/XAP-XMLAutomatedParser/src/main/resources/sampleFiles/SampleBondsXSD_Short.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">	
		   
   <!-- Starting Element which can have multiple Instrument Tags -->
   <xsd:element name="StartingTag" 		type="StartingTag"/>
   
   <xsd:complexType name="StartingTag">
      <xsd:sequence>
         <xsd:element name="Instrument" type="Instrument" minOccurs="0" maxOccurs="unbounded"/>
      </xsd:sequence>
   </xsd:complexType>		   
		   
<!--    <xsd:element name="Instrument" type="Instrument"/> -->

   <xsd:complexType name="Instrument">
      <xsd:sequence>
         <xsd:element name="instrumentId" minOccurs="1" maxOccurs="1" type="xsd:long"/>
         <xsd:element name="datasetId" minOccurs="1" maxOccurs="1" type="xsd:long"/>
         <xsd:element name="version" minOccurs="1" maxOccurs="1" type="xsd:long"/>
         <xsd:element name="newIssue" minOccurs="0" maxOccurs="1">
            <xsd:simpleType>
               <xsd:restriction base="xsd:string">
                  <xsd:maxLength value="20"/>
               </xsd:restriction>
            </xsd:simpleType>
         </xsd:element>
         <xsd:element name="instrumentGrade" minOccurs="1" maxOccurs="1">
            <xsd:simpleType>
               <xsd:restriction base="xsd:string">
                  <xsd:maxLength value="25"/>
               </xsd:restriction>
            </xsd:simpleType>
         </xsd:element>
         <xsd:element name="lastModifiedDate" minOccurs="1" maxOccurs="1" type="xsd:dateTime"/>
         <xsd:element name="source" minOccurs="1" maxOccurs="1">
            <xsd:simpleType>
               <xsd:restriction base="xsd:string">
                  <xsd:maxLength value="30"/>
               </xsd:restriction>
            </xsd:simpleType>
         </xsd:element>
         <xsd:element name="amtIssuedPublic" minOccurs="0" maxOccurs="1" type="xsd:double"/>
         <xsd:element name="isBondLinked" minOccurs="0" maxOccurs="1" type="xsd:boolean"/>
         <xsd:element name="benchmarkISIN" minOccurs="0" maxOccurs="1">
            <xsd:simpleType>
               <xsd:restriction base="xsd:string">
                  <xsd:maxLength value="12"/>
               </xsd:restriction>
            </xsd:simpleType>
         </xsd:element>
         <xsd:element name="businessDayConvention" minOccurs="0" maxOccurs="1">
            <xsd:simpleType>
               <xsd:restriction base="xsd:string">
                  <xsd:maxLength value="100"/>
               </xsd:restriction>
            </xsd:simpleType>
         </xsd:element>
         <xsd:element name="classification" minOccurs="0" maxOccurs="1">
            <xsd:simpleType>
               <xsd:restriction base="xsd:string">
                  <xsd:maxLength value="100"/>
               </xsd:restriction>
            </xsd:simpleType>
         </xsd:element>
         <xsd:element name="classificationSubType" minOccurs="0" maxOccurs="1">
            <xsd:simpleType>
               <xsd:restriction base="xsd:string">
                  <xsd:maxLength value="100"/>
               </xsd:restriction>
            </xsd:simpleType>
         </xsd:element>
         <xsd:element name="priceAtIssue" minOccurs="0" maxOccurs="1" type="xsd:double"/>
         <xsd:element name="issueSize" minOccurs="0" maxOccurs="1" type="xsd:double"/>
         <xsd:element name="issueCountry" minOccurs="0" maxOccurs="1">
            <xsd:simpleType>
               <xsd:restriction base="xsd:string">
                  <xsd:maxLength value="3"/>
               </xsd:restriction>
            </xsd:simpleType>
         </xsd:element>
         <xsd:element name="issueDate" minOccurs="0" maxOccurs="1" type="xsd:date"/>
         <xsd:element name="issueName" minOccurs="0" maxOccurs="1">
            <xsd:simpleType>
               <xsd:restriction base="xsd:string">
                  <xsd:maxLength value="200"/>
               </xsd:restriction>
            </xsd:simpleType>
         </xsd:element>
         <xsd:element name="issueType" minOccurs="0" maxOccurs="1">
            <xsd:simpleType>
               <xsd:restriction base="xsd:string">
                  <xsd:maxLength value="200"/>
               </xsd:restriction>
            </xsd:simpleType>
         </xsd:element>
         <xsd:element name="lastCouponDate" minOccurs="0" maxOccurs="1" type="xsd:date"/>
         <xsd:element name="marketRegion" minOccurs="0" maxOccurs="1">
            <xsd:simpleType>
               <xsd:restriction base="xsd:string">
                  <xsd:maxLength value="100"/>
               </xsd:restriction>
            </xsd:simpleType>
         </xsd:element>
         <xsd:element name="maturityAmount" minOccurs="0" maxOccurs="1" type="xsd:double"/>
         <xsd:element name="maturityDate" minOccurs="0" maxOccurs="1" type="xsd:date"/>
         <xsd:element name="maturityPrice" minOccurs="0" maxOccurs="1" type="xsd:decimal"/>
          <xsd:element name="assetExchange" minOccurs="0" maxOccurs="unbounded" type="AssetExchange"/>
		  <xsd:element name="CallSchedule" 	minOccurs="0" maxOccurs="unbounded" type="CallSchedule"/>
		  <xsd:element name="PutSchedule" 	minOccurs="0" maxOccurs="unbounded" type="PutSchedule"/>
		  <xsd:element name="Ratings" 		minOccurs="0" maxOccurs="unbounded" type="Ratings"/>
		  <xsd:element name="Redemption" 	minOccurs="0" maxOccurs="unbounded" type="Redemption"/>

      </xsd:sequence>
   </xsd:complexType>
 
   <xsd:complexType name="AssetExchange">
      <xsd:sequence>
         <xsd:element name="assetExchangeSource" minOccurs="0" maxOccurs="1">
            <xsd:simpleType>
               <xsd:restriction base="xsd:string">
                  <xsd:maxLength value="30"/>
               </xsd:restriction>
            </xsd:simpleType>
         </xsd:element>
         <xsd:element name="exchangeCode" minOccurs="0" maxOccurs="1">
            <xsd:simpleType>
               <xsd:restriction base="xsd:string">
                  <xsd:maxLength value="100"/>
               </xsd:restriction>
            </xsd:simpleType>
         </xsd:element>
         <xsd:element name="mic" minOccurs="0" maxOccurs="1">
            <xsd:simpleType>
               <xsd:restriction base="xsd:string">
                  <xsd:maxLength value="100"/>
               </xsd:restriction>
            </xsd:simpleType>
         </xsd:element>
         <xsd:element name="micStatus" minOccurs="0" maxOccurs="1" type="xsd:boolean"/>
         <xsd:element name="listingEffectiveDate" minOccurs="0" maxOccurs="1" type="xsd:date"/>
         <xsd:element name="bbgExchangeId" minOccurs="0" maxOccurs="1">
            <xsd:simpleType>
               <xsd:restriction base="xsd:string">
                  <xsd:maxLength value="50"/>
               </xsd:restriction>
            </xsd:simpleType>
         </xsd:element>
         <xsd:element name="bbgExchangeTicker" minOccurs="0" maxOccurs="1">
            <xsd:simpleType>
               <xsd:restriction base="xsd:string">
                  <xsd:maxLength value="50"/>
               </xsd:restriction>
            </xsd:simpleType>
         </xsd:element>
         <xsd:element name="cityOfListing" minOccurs="0" maxOccurs="1">
            <xsd:simpleType>
               <xsd:restriction base="xsd:string">
                  <xsd:maxLength value="100"/>
               </xsd:restriction>
            </xsd:simpleType>
         </xsd:element>
         <xsd:element name="countryOfListing" minOccurs="0" maxOccurs="1">
            <xsd:simpleType>
               <xsd:restriction base="xsd:string">
                  <xsd:maxLength value="10"/>
               </xsd:restriction>
            </xsd:simpleType>
         </xsd:element>
         <xsd:element name="delistingDate" minOccurs="0" maxOccurs="1" type="xsd:date"/>
         <xsd:element name="exchangeName" minOccurs="0" maxOccurs="1">
            <xsd:simpleType>
               <xsd:restriction base="xsd:string">
                  <xsd:maxLength value="100"/>
               </xsd:restriction>
            </xsd:simpleType>
         </xsd:element>
         <xsd:element name="listingStatus" minOccurs="0" maxOccurs="1">
            <xsd:simpleType>
               <xsd:restriction base="xsd:string">
                  <xsd:maxLength value="50"/>
               </xsd:restriction>
            </xsd:simpleType>
         </xsd:element>
         <xsd:element name="isPrimaryListing" minOccurs="0" maxOccurs="1" type="xsd:boolean"/>
         <xsd:element name="cityOfSubMarket" minOccurs="0" maxOccurs="1">
            <xsd:simpleType>
               <xsd:restriction base="xsd:string">
                  <xsd:maxLength value="100"/>
               </xsd:restriction>
            </xsd:simpleType>
         </xsd:element>
         <xsd:element name="subMarketExchange" minOccurs="0" maxOccurs="1">
            <xsd:simpleType>
               <xsd:restriction base="xsd:string">
                  <xsd:maxLength value="100"/>
               </xsd:restriction>
            </xsd:simpleType>
         </xsd:element>
         <xsd:element name="subMarketMic" minOccurs="0" maxOccurs="1">
            <xsd:simpleType>
               <xsd:restriction base="xsd:string">
                  <xsd:maxLength value="10"/>
               </xsd:restriction>
            </xsd:simpleType>
         </xsd:element>
         <xsd:element name="subMarketMicStatus" minOccurs="0" maxOccurs="1">
            <xsd:simpleType>
               <xsd:restriction base="xsd:string">
                  <xsd:maxLength value="50"/>
               </xsd:restriction>
            </xsd:simpleType>
         </xsd:element>
      </xsd:sequence>
   </xsd:complexType>
   
   <xsd:complexType name="CallSchedule">
      <xsd:sequence>
         <xsd:element name="callScheduleSource" minOccurs="0" maxOccurs="1">
            <xsd:simpleType>
               <xsd:restriction base="xsd:string">
                  <xsd:maxLength value="30"/>
               </xsd:restriction>
            </xsd:simpleType>
         </xsd:element>
         <xsd:element name="isCallDefeased" minOccurs="0" maxOccurs="1" type="xsd:boolean"/>
         <xsd:element name="callStartDate" minOccurs="0" maxOccurs="1" type="xsd:date"/>
         <xsd:element name="callEndDate" minOccurs="0" maxOccurs="1" type="xsd:date"/>
         <xsd:element name="callValidity" minOccurs="0" maxOccurs="1" type="xsd:long"/>
         <xsd:element name="callFrequencyCode" minOccurs="0" maxOccurs="1">
            <xsd:simpleType>
               <xsd:restriction base="xsd:string">
                  <xsd:maxLength value="100"/>
               </xsd:restriction>
            </xsd:simpleType>
         </xsd:element>
         <xsd:element name="callPrice" minOccurs="0" maxOccurs="1" type="xsd:decimal"/>
         <xsd:element name="callMaxNoticeDays" minOccurs="0" maxOccurs="1" type="xsd:long"/>
         <xsd:element name="callMinNoticeDays" minOccurs="0" maxOccurs="1" type="xsd:long"/>    
         <xsd:element name="isCompoundAccretedValue" minOccurs="0" maxOccurs="1" type="xsd:boolean"/>
         <xsd:element name="makewholeSpread" minOccurs="0" maxOccurs="1" type="xsd:double"/>
         <xsd:element name="softCallConversionPercent" minOccurs="0" maxOccurs="1" type="xsd:double"/>
         <xsd:element name="softCallConversionPercentPremium" minOccurs="0" maxOccurs="1"
                      type="xsd:double"/>
         <xsd:element name="softCallDays" minOccurs="0" maxOccurs="1" type="xsd:double"/>
         <xsd:element name="softCallTriggerValue" minOccurs="0" maxOccurs="1" type="xsd:double"/>
      </xsd:sequence>
   </xsd:complexType>
   
   <xsd:complexType name="PutSchedule">
      <xsd:sequence>
         <xsd:element name="putScheduleSource" minOccurs="0" maxOccurs="1">
            <xsd:simpleType>
               <xsd:restriction base="xsd:string">
                  <xsd:maxLength value="30"/>
               </xsd:restriction>
            </xsd:simpleType>
         </xsd:element>
         <xsd:element name="putStartDate" minOccurs="0" maxOccurs="1" type="xsd:date"/>
         <xsd:element name="putEndDate" minOccurs="0" maxOccurs="1" type="xsd:date"/>
         <xsd:element name="putValidity" minOccurs="0" maxOccurs="1" type="xsd:long"/>
         <xsd:element name="putFee" minOccurs="0" maxOccurs="1" type="xsd:double"/>
         <xsd:element name="putFrequencyCode" minOccurs="0" maxOccurs="1">
            <xsd:simpleType>
               <xsd:restriction base="xsd:string">
                  <xsd:maxLength value="100"/>
               </xsd:restriction>
            </xsd:simpleType>
         </xsd:element>
         <xsd:element name="putPrice" minOccurs="0" maxOccurs="1" type="xsd:decimal"/>
         <xsd:element name="isSpecialPut" minOccurs="0" maxOccurs="1" type="xsd:boolean"/>
         <xsd:element name="putMaxNoticeDays" minOccurs="0" maxOccurs="1" type="xsd:long"/>
         <xsd:element name="putMinNoticeDays" minOccurs="0" maxOccurs="1" type="xsd:long"/>
         <xsd:element name="putNoticeDaysConvention" minOccurs="0" maxOccurs="1">
            <xsd:simpleType>
               <xsd:restriction base="xsd:string">
                  <xsd:maxLength value="100"/>
               </xsd:restriction>
            </xsd:simpleType>
         </xsd:element>
        </xsd:sequence>
   </xsd:complexType>
 
   <xsd:complexType name="Ratings">
      <xsd:sequence>
         <xsd:element name="ratingType" minOccurs="0" maxOccurs="1">
            <xsd:simpleType>
               <xsd:restriction base="xsd:string">
                  <xsd:maxLength value="100"/>
               </xsd:restriction>
            </xsd:simpleType>
         </xsd:element>
         <xsd:element name="ratingProvider" minOccurs="0" maxOccurs="1">
            <xsd:simpleType>
               <xsd:restriction base="xsd:string">
                  <xsd:maxLength value="100"/>
               </xsd:restriction>
            </xsd:simpleType>
         </xsd:element>
         <xsd:element name="ratingEffectiveDate" minOccurs="0" maxOccurs="1" type="xsd:date"/>
         <xsd:element name="rating" minOccurs="0" maxOccurs="1">
            <xsd:simpleType>
               <xsd:restriction base="xsd:string">
                  <xsd:maxLength value="100"/>
               </xsd:restriction>
            </xsd:simpleType>
         </xsd:element>
         <xsd:element name="ratingsSource" minOccurs="0" maxOccurs="1">
            <xsd:simpleType>
               <xsd:restriction base="xsd:string">
                  <xsd:maxLength value="30"/>
               </xsd:restriction>
            </xsd:simpleType>
         </xsd:element>
         <xsd:element name="ratingOutlook" minOccurs="0" maxOccurs="1">
            <xsd:simpleType>
               <xsd:restriction base="xsd:string">
                  <xsd:maxLength value="50"/>
               </xsd:restriction>
            </xsd:simpleType>
         </xsd:element>
         <xsd:element name="ratingWatch" minOccurs="0" maxOccurs="1">
            <xsd:simpleType>
               <xsd:restriction base="xsd:string">
                  <xsd:maxLength value="50"/>
               </xsd:restriction>
            </xsd:simpleType>
         </xsd:element>
         <xsd:element name="ratingEndDate" minOccurs="0" maxOccurs="1" type="xsd:date"/>
         <xsd:element name="isIssuerOrInstrumentRating" minOccurs="0" maxOccurs="1">
            <xsd:simpleType>
               <xsd:restriction base="xsd:string">
                  <xsd:maxLength value="20"/>
               </xsd:restriction>
            </xsd:simpleType>
         </xsd:element>
      </xsd:sequence>
   </xsd:complexType>
   
   <xsd:complexType name="Redemption">
      <xsd:sequence>
         <xsd:element name="redemptionSource" minOccurs="0" maxOccurs="1">
            <xsd:simpleType>
               <xsd:restriction base="xsd:string">
                  <xsd:maxLength value="30"/>
               </xsd:restriction>
            </xsd:simpleType>
         </xsd:element>
         <xsd:element name="amount" minOccurs="0" maxOccurs="1" type="xsd:double"/>
         <xsd:element name="redemptionMethod" minOccurs="0" maxOccurs="1">
            <xsd:simpleType>
               <xsd:restriction base="xsd:string">
                  <xsd:maxLength value="100"/>
               </xsd:restriction>
            </xsd:simpleType>
         </xsd:element>
         <xsd:element name="redemptionStrikePrice" minOccurs="0" maxOccurs="1" type="xsd:decimal"/>
         <xsd:element name="redemptionValue" minOccurs="0" maxOccurs="1" type="xsd:double"/>
         <xsd:element name="redenominatedExchangeRate" minOccurs="0" maxOccurs="1" type="xsd:double"/>
         <xsd:element name="refundingDatedDate" minOccurs="0" maxOccurs="1" type="xsd:date"/>
         <xsd:element name="refundingSettleDate" minOccurs="0" maxOccurs="1" type="xsd:date"/>
         <xsd:element name="currAmtOutstandingEffectiveDate" minOccurs="0" maxOccurs="1" type="xsd:date"/>
         <xsd:element name="redemptionCashFlow" minOccurs="0" maxOccurs="1" type="xsd:double"/>
         <xsd:element name="reofferReopenPrice" minOccurs="0" maxOccurs="1" type="xsd:double"/>
         <xsd:element name="reofferReopenSpread" minOccurs="0" maxOccurs="1" type="xsd:decimal"/>
         <xsd:element name="reofferReopenYield" minOccurs="0" maxOccurs="1" type="xsd:decimal"/>
         <xsd:element name="caAnnouncementDate" minOccurs="0" maxOccurs="1" type="xsd:date"/>
         <xsd:element name="amountOutstanding" minOccurs="0" maxOccurs="1" type="xsd:double"/>
      </xsd:sequence>
   </xsd:complexType>

</xsd:schema>

=== nitinsingh008/XML-Analytics/XAP-XMLAutomatedParser/src/main/resources/SampleBondsXSD_Short.xml
<?xml version="1.0" encoding="UTF-8"?>
<StartingTag xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="SampleBondsXSD_Short.xsd">
  <Instrument>
    <instrumentId>10</instrumentId>
    <datasetId>0</datasetId>
    <version>0</version>
    <newIssue>newIssue</newIssue>
    <instrumentGrade>instrumentGrade</instrumentGrade>
    <lastModifiedDate>2001-12-31T12:00:00</lastModifiedDate>
    <source>source</source>
    <amtIssuedPublic>0.0</amtIssuedPublic>
    <isBondLinked>true</isBondLinked>
    <benchmarkISIN>ISIN</benchmarkISIN>
    <businessDayConvention>businessDayConvention</businessDayConvention>
    <classification>classification</classification>
    <classificationSubType>classificationSubType</classificationSubType>
    <priceAtIssue>0.0</priceAtIssue>
    <issueSize>0.0</issueSize>
    <issueCountry>USD</issueCountry>
    <issueDate>2001-01-01</issueDate>
    <issueName>issueName</issueName>
    <issueType>issueType</issueType>
    <lastCouponDate>2001-01-01</lastCouponDate>
    <marketRegion>marketRegion</marketRegion>
    <maturityAmount>0.0</maturityAmount>
    <maturityDate>2001-01-01</maturityDate>
    <maturityPrice>0.0</maturityPrice>
    <assetExchange>
      <assetExchangeSource>assetExchangeSource</assetExchangeSource>
      <exchangeCode>exchangeCode</exchangeCode>
      <mic>MI</mic>
      <micStatus>true</micStatus>
      <listingEffectiveDate>2001-01-01</listingEffectiveDate>
      <bbgExchangeId>bbgExchangeId</bbgExchangeId>
      <bbgExchangeTicker>bbgExchangeTicker</bbgExchangeTicker>
      <cityOfListing>cityOfListing</cityOfListing>
      <countryOfListing>USD</countryOfListing>
      <delistingDate>2001-01-01</delistingDate>
      <exchangeName>exchangeName</exchangeName>
      <listingStatus>listingStatus</listingStatus>
      <isPrimaryListing>true</isPrimaryListing>
      <cityOfSubMarket>cityOfSubMarket</cityOfSubMarket>
      <subMarketExchange>subMarketExchange</subMarketExchange>
      <subMarketMic>MIC</subMarketMic>
      <subMarketMicStatus>subMarketMicStatus</subMarketMicStatus>
    </assetExchange>
    <CallSchedule>
      <callScheduleSource>callScheduleSource</callScheduleSource>
      <isCallDefeased>true</isCallDefeased>
      <callStartDate>2001-01-01</callStartDate>
      <callEndDate>2001-01-01</callEndDate>
      <callValidity>0</callValidity>
      <callFrequencyCode>callFrequencyCode</callFrequencyCode>
      <callPrice>0.0</callPrice>
      <callMaxNoticeDays>0</callMaxNoticeDays>
      <callMinNoticeDays>0</callMinNoticeDays>
      <isCompoundAccretedValue>true</isCompoundAccretedValue>
      <makewholeSpread>0.0</makewholeSpread>
      <softCallConversionPercent>0.0</softCallConversionPercent>
      <softCallConversionPercentPremium>0.0</softCallConversionPercentPremium>
      <softCallDays>0.0</softCallDays>
      <softCallTriggerValue>0.0</softCallTriggerValue>
    </CallSchedule>
    <PutSchedule>
      <putScheduleSource>putScheduleSource</putScheduleSource>
      <putStartDate>2001-01-01</putStartDate>
      <putEndDate>2001-01-01</putEndDate>
      <putValidity>0</putValidity>
      <putFee>0.0</putFee>
      <putFrequencyCode>putFrequencyCode</putFrequencyCode>
      <putPrice>0.0</putPrice>
      <isSpecialPut>true</isSpecialPut>
      <putMaxNoticeDays>0</putMaxNoticeDays>
      <putMinNoticeDays>0</putMinNoticeDays>
      <putNoticeDaysConvention>putNoticeDaysConvention</putNoticeDaysConvention>
    </PutSchedule>
    <Ratings>
      <ratingType>ratingType</ratingType>
      <ratingProvider>ratingProvider</ratingProvider>
      <ratingEffectiveDate>2001-01-01</ratingEffectiveDate>
      <rating>rating</rating>
      <ratingsSource>ratingsSource</ratingsSource>
      <ratingOutlook>ratingOutlook</ratingOutlook>
      <ratingWatch>ratingWatch</ratingWatch>
      <ratingEndDate>2001-01-01</ratingEndDate>
      <isIssuerOrInstrumentRating>AA</isIssuerOrInstrumentRating>
    </Ratings>
    <Redemption>
      <redemptionSource>redemptionSource</redemptionSource>
      <amount>0.0</amount>
      <redemptionMethod>redemptionMethod</redemptionMethod>
      <redemptionStrikePrice>0.0</redemptionStrikePrice>
      <redemptionValue>0.0</redemptionValue>
      <redenominatedExchangeRate>0.0</redenominatedExchangeRate>
      <refundingDatedDate>2001-01-01</refundingDatedDate>
      <refundingSettleDate>2001-01-01</refundingSettleDate>
      <currAmtOutstandingEffectiveDate>2001-01-01</currAmtOutstandingEffectiveDate>
      <redemptionCashFlow>0.0</redemptionCashFlow>
      <reofferReopenPrice>0.0</reofferReopenPrice>
      <reofferReopenSpread>0.0</reofferReopenSpread>
      <reofferReopenYield>0.0</reofferReopenYield>
      <caAnnouncementDate>2001-01-01</caAnnouncementDate>
      <amountOutstanding>0.0</amountOutstanding>
    </Redemption>
  </Instrument>
  <Instrument>
    <instrumentId>11</instrumentId>
    <datasetId>0</datasetId>
    <version>0</version>
    <newIssue>newIssue</newIssue>
    <instrumentGrade>instrumentGrade</instrumentGrade>
    <lastModifiedDate>2001-12-31T12:00:00</lastModifiedDate>
    <source>source</source>
    <amtIssuedPublic>0.0</amtIssuedPublic>
    <isBondLinked>true</isBondLinked>
    <benchmarkISIN>ISIN</benchmarkISIN>
    <businessDayConvention>businessDayConvention</businessDayConvention>
    <classification>classification</classification>
    <classificationSubType>classificationSubType</classificationSubType>
    <priceAtIssue>0.0</priceAtIssue>
    <issueSize>0.0</issueSize>
    <issueCountry>USD</issueCountry>
    <issueDate>2001-01-01</issueDate>
    <issueName>issueName</issueName>
    <issueType>issueType</issueType>
    <lastCouponDate>2001-01-01</lastCouponDate>
    <marketRegion>marketRegion</marketRegion>
    <maturityAmount>0.0</maturityAmount>
    <maturityDate>2001-01-01</maturityDate>
    <maturityPrice>0.0</maturityPrice>
    <assetExchange>
      <assetExchangeSource>assetExchangeSource</assetExchangeSource>
      <exchangeCode>exchangeCode</exchangeCode>
      <mic>MI</mic>
      <micStatus>true</micStatus>
      <listingEffectiveDate>2001-01-01</listingEffectiveDate>
      <bbgExchangeId>bbgExchangeId</bbgExchangeId>
      <bbgExchangeTicker>bbgExchangeTicker</bbgExchangeTicker>
      <cityOfListing>cityOfListing</cityOfListing>
      <countryOfListing>USD</countryOfListing>
      <delistingDate>2001-01-01</delistingDate>
      <exchangeName>exchangeName</exchangeName>
      <listingStatus>listingStatus</listingStatus>
      <isPrimaryListing>true</isPrimaryListing>
      <cityOfSubMarket>cityOfSubMarket</cityOfSubMarket>
      <subMarketExchange>subMarketExchange</subMarketExchange>
      <subMarketMic>MIC</subMarketMic>
      <subMarketMicStatus>subMarketMicStatus</subMarketMicStatus>
    </assetExchange>
    <CallSchedule>
      <callScheduleSource>callScheduleSource</callScheduleSource>
      <isCallDefeased>true</isCallDefeased>
      <callStartDate>2001-01-01</callStartDate>
      <callEndDate>2001-01-01</callEndDate>
      <callValidity>0</callValidity>
      <callFrequencyCode>callFrequencyCode</callFrequencyCode>
      <callPrice>0.0</callPrice>
      <callMaxNoticeDays>0</callMaxNoticeDays>
      <callMinNoticeDays>0</callMinNoticeDays>
      <isCompoundAccretedValue>true</isCompoundAccretedValue>
      <makewholeSpread>0.0</makewholeSpread>
      <softCallConversionPercent>0.0</softCallConversionPercent>
      <softCallConversionPercentPremium>0.0</softCallConversionPercentPremium>
      <softCallDays>0.0</softCallDays>
      <softCallTriggerValue>0.0</softCallTriggerValue>
    </CallSchedule>
    <PutSchedule>
      <putScheduleSource>putScheduleSource</putScheduleSource>
      <putStartDate>2001-01-01</putStartDate>
      <putEndDate>2001-01-01</putEndDate>
      <putValidity>0</putValidity>
      <putFee>0.0</putFee>
      <putFrequencyCode>putFrequencyCode</putFrequencyCode>
      <putPrice>0.0</putPrice>
      <isSpecialPut>true</isSpecialPut>
      <putMaxNoticeDays>0</putMaxNoticeDays>
      <putMinNoticeDays>0</putMinNoticeDays>
      <putNoticeDaysConvention>putNoticeDaysConvention</putNoticeDaysConvention>
    </PutSchedule>
    <Ratings>
      <ratingType>ratingType</ratingType>
      <ratingProvider>ratingProvider</ratingProvider>
      <ratingEffectiveDate>2001-01-01</ratingEffectiveDate>
      <rating>rating</rating>
      <ratingsSource>ratingsSource</ratingsSource>
      <ratingOutlook>ratingOutlook</ratingOutlook>
      <ratingWatch>ratingWatch</ratingWatch>
      <ratingEndDate>2001-01-01</ratingEndDate>
      <isIssuerOrInstrumentRating>AA</isIssuerOrInstrumentRating>
    </Ratings>
    <Redemption>
      <redemptionSource>redemptionSource</redemptionSource>
      <amount>0.0</amount>
      <redemptionMethod>redemptionMethod</redemptionMethod>
      <redemptionStrikePrice>0.0</redemptionStrikePrice>
      <redemptionValue>0.0</redemptionValue>
      <redenominatedExchangeRate>0.0</redenominatedExchangeRate>
      <refundingDatedDate>2001-01-01</refundingDatedDate>
      <refundingSettleDate>2001-01-01</refundingSettleDate>
      <currAmtOutstandingEffectiveDate>2001-01-01</currAmtOutstandingEffectiveDate>
      <redemptionCashFlow>0.0</redemptionCashFlow>
      <reofferReopenPrice>0.0</reofferReopenPrice>
      <reofferReopenSpread>0.0</reofferReopenSpread>
      <reofferReopenYield>0.0</reofferReopenYield>
      <caAnnouncementDate>2001-01-01</caAnnouncementDate>
      <amountOutstanding>0.0</amountOutstanding>
    </Redemption>
  </Instrument>  
</StartingTag>
